# Generated by Django 4.0 on 2023-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Live Music', max_length=100),
        ),
    ]
