# Generated by Django 4.0 on 2023-07-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0003_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/1024px-No_image_available.svg.png'),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_url',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/1024px-No_image_available.svg.png'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='Event', max_length=100),
        ),
    ]
