# Generated by Django 4.0 on 2023-07-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0005_rename_artist_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickit.event')),
            ],
        ),
    ]
